#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# idk lmao
# without this line QT apps take forever to start
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# Make sure screen gets locked when lid is closed
light-locker --lock-on-lid &

# playerctl
playerctld daemon

# blur
picom --experimental-backends &

# screenshots
flameshot &

# turn off beeps
xset b off 
xset b 0 0 0

# Curser rate
xset r rate 250 45

# turn off screen saver
xset dpms 0 0 0
xset s off

# align two monitors
xrandr --output eDP-1 --auto --output HDMI-1 --right-of eDP-1

# mirror two monitors
# xrandr --output eDP-1 --auto --output HDMI-1 --same-as eDP-1

# Use qt5
export QT_QPA_PLATFORMTHEME="qt5ct"

# Enable tap to click on touchpad
xinput set-prop "Synaptics TM3383-002" "libinput Tapping Enabled" 1

# https://wiki.archlinux.org/index.php/arduino#Application_not_resizing_with_WM,_menus_immediately_closing
wmname compiz
export AWT_TOOLKIT=MToolkit

# MATLAB
export MATLAB_JAVA=/usr/lib/jvm/java-8-openjdk/jre
export _JAVA_AWT_WM_NONREPARENTING=1

# Fix segfault during Burp Suite startup
export app_java_home=/usr/lib/jvm/java-17-openjdk $HOME/.local/share/BurpSuiteCommunity

# numlock
numlockx &

# Discord custom css
$HOME/.local/bin/discocss &

# bspwm
sxhkd &
exec bspwm
