#! /bin/sh
bspc rule -r "*"
# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d ひ ふ み よ い む な や こ と
bspc monitor HDMI1 -d ひ ふ み よ い む な や こ と
pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/scripts/launch.sh

bspc config border_width         2
bspc config window_gap           10
#bspc config window_gap           12
bspc config top_padding          27
bspc config bottom_padding		 0

bspc config split_ratio          0.50
# bspc config split_ratio	 0.618 # golden ratio
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius		 5

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
