#! /bin/sh
bspc rule -r "*"
bspc monitor -d ひ ふ み よ い む な や こ と
bspc monitor HDMI-1 -d ひ ふ み よ い む な や こ と
pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/scripts/launch.sh

bspc config border_width         0
bspc config window_gap           10
bspc config top_padding          27
bspc config bottom_padding		 0

bspc config split_ratio          0.50
# bspc config split_ratio	 0.618 # golden ratio
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius		 0
bspc config focus_follows_pointer true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color7"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

/usr/bin/rofi -no-lazy-grab -show drun -theme $HOME/.config/rofi/style_11.rasi
