#!/bin/bash
awk '/^[a-zA-Z]/ && last {print "<small>",$0,"\t",last,"</small>"} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc | column -t -s $'\t' | rofi -no-lazy-grab -markup-rows -dmenu -i -theme $HOME/.config/rofi/style_6.rasi
